// <auto-generated />
using BarberApp.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaberApp.Persistence.Migrations
{
    [DbContext(typeof(BarberAppContext))]
    [Migration("20240117191202_initial_barber_migration")]
    partial class initial_barber_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BarberApp.Domain.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("ClientId");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("BarberApp.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employeess", (string)null);
                });

            modelBuilder.Entity("BarberApp.Domain.Entities.LegalPerson", b =>
                {
                    b.Property<int>("LegalPersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LegalPersonId");

                    b.ToTable("LegalPersons", (string)null);
                });

            modelBuilder.Entity("BarberApp.Domain.Entities.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("PersonId");

                    b.ToTable("Persons", (string)null);
                });

            modelBuilder.Entity("BarberApp.Domain.Entities.PhysicalPerson", b =>
                {
                    b.Property<int>("PhysicalPersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PhysicalPersonId");

                    b.ToTable("PhysicalPersonss", (string)null);
                });

            modelBuilder.Entity("BarberApp.Domain.Entities.Person", b =>
                {
                    b.HasOne("BarberApp.Domain.Entities.Client", "Client")
                        .WithOne("Person")
                        .HasForeignKey("BarberApp.Domain.Entities.Person", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberApp.Domain.Entities.Employee", "Employee")
                        .WithOne("Person")
                        .HasForeignKey("BarberApp.Domain.Entities.Person", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberApp.Domain.Entities.LegalPerson", "LegalPerson")
                        .WithOne("Person")
                        .HasForeignKey("BarberApp.Domain.Entities.Person", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberApp.Domain.Entities.PhysicalPerson", "PhysicalPerson")
                        .WithOne("Person")
                        .HasForeignKey("BarberApp.Domain.Entities.Person", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Employee");

                    b.Navigation("LegalPerson");

                    b.Navigation("PhysicalPerson");
                });

            modelBuilder.Entity("BarberApp.Domain.Entities.Client", b =>
                {
                    b.Navigation("Person")
                        .IsRequired();
                });

            modelBuilder.Entity("BarberApp.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Person")
                        .IsRequired();
                });

            modelBuilder.Entity("BarberApp.Domain.Entities.LegalPerson", b =>
                {
                    b.Navigation("Person")
                        .IsRequired();
                });

            modelBuilder.Entity("BarberApp.Domain.Entities.PhysicalPerson", b =>
                {
                    b.Navigation("Person")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
