-- MySQL Script generated by MySQL Workbench
-- Tue Jan  9 11:20:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `cod_pessoa` INT NOT NULL,
  PRIMARY KEY (`cod_pessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa_Fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa_Fisica` (
  `cod_pessoa` INT NOT NULL,
  `cpf` VARCHAR(14) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_pessoa`),
  CONSTRAINT `idpfisica`
    FOREIGN KEY (`cod_pessoa`)
    REFERENCES `mydb`.`Pessoa` (`cod_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa_Juridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa_Juridica` (
  `cod_pessoa` INT NOT NULL,
  `cnpj` VARCHAR(18) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_pessoa`),
  CONSTRAINT `idpjuridica`
    FOREIGN KEY (`cod_pessoa`)
    REFERENCES `mydb`.`Pessoa` (`cod_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `cod_cliente` INT NOT NULL,
  `cod_pessoa` INT NULL DEFAULT NULL,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_cliente`),
  INDEX `idcliente_idx` (`cod_pessoa` ASC) VISIBLE,
  CONSTRAINT `idcliente`
    FOREIGN KEY (`cod_pessoa`)
    REFERENCES `mydb`.`Pessoa` (`cod_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Solicitacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Solicitacoes` (
  `cod_solicitacao` INT NOT NULL,
  `cod_cliente` INT NULL DEFAULT NULL,
  `timestamp` VARCHAR(45) NULL DEFAULT NULL,
  `valor_solicitado` FLOAT NULL DEFAULT NULL,
  `Solicitacoescol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_solicitacao`),
  INDEX `idsolicitacoes_idx` (`cod_cliente` ASC) VISIBLE,
  CONSTRAINT `idsolicitacoes`
    FOREIGN KEY (`cod_cliente`)
    REFERENCES `mydb`.`Clientes` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `cod_funcionario` INT NOT NULL,
  `cod_pessoa` INT NULL DEFAULT NULL,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `telefone` VARCHAR(11) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_funcionario`),
  INDEX `idfuncionario_idx` (`cod_pessoa` ASC) VISIBLE,
  CONSTRAINT `idfuncionario`
    FOREIGN KEY (`cod_pessoa`)
    REFERENCES `mydb`.`Pessoa` (`cod_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servico` (
  `cod_servico` INT NOT NULL,
  `cod_solicitacao` INT NULL DEFAULT NULL,
  `cod_funcionario` INT NULL DEFAULT NULL,
  `tipo` VARCHAR(20) NULL DEFAULT NULL,
  `valor` FLOAT NULL DEFAULT NULL,
  `quantidade` INT NULL DEFAULT NULL,
  `timestamp` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cod_servico`),
  INDEX `idservico_idx` (`cod_funcionario` ASC) VISIBLE,
  INDEX `idservico_idx1` (`cod_solicitacao` ASC) VISIBLE,
  CONSTRAINT `idservico`
    FOREIGN KEY (`cod_funcionario`)
    REFERENCES `mydb`.`Funcionario` (`cod_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idservico`
    FOREIGN KEY (`cod_solicitacao`)
    REFERENCES `mydb`.`Solicitacoes` (`cod_solicitacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
